force-app/main/default/objects/Board__c/Board__c.object-meta.xml
<CustomObject>
    <description>This is used for storing projects or work against.</description>
    <label>Board</label>
    <nameField>
        <label>Board Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Boards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Board_Tags__c/Board_Tags__c.object-meta.xml
<CustomObject>
    <description>This object is used to setup tags on a project</description>
    <label>Board Tag</label>
    <nameField>
        <label>Board Tags Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Board Tags</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Board_Tags__c/fields/Board__c.field-meta.xml
<CustomField>
    <fullName>Board__c</fullName>
    <label>Board</label>
    <referenceTo>Board__c</referenceTo>
    <relationshipLabel>Board Tags</relationshipLabel>
    <relationshipName>Board_Tags</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Board_Tags__c/fields/Colour__c.field-meta.xml
<CustomField>
    <fullName>Colour__c</fullName>
    <label>Colour</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aqua</fullName>
            </value>
            <value>
                <fullName>Black</fullName>
            </value>
            <value>
                <fullName>Blue</fullName>
            </value>
            <value>
                <fullName>Brown</fullName>
            </value>
            <value>
                <fullName>DarkGreen</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
            <value>
                <fullName>Grey</fullName>
            </value>
            <value>
                <fullName>Maroon</fullName>
            </value>
            <value>
                <fullName>Navy</fullName>
            </value>
            <value>
                <fullName>Orange</fullName>
            </value>
            <value>
                <fullName>Pink</fullName>
            </value>
            <value>
                <fullName>Purple</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/boardLWCTagManagement.cls
/**
 * @description       : 
 * @author            : daniel@hyphen8.com
 * @last modified on  : 02/02/2021
 * @last modified by  : daniel@hyphen8.com
 * Modifications Log 
 * Ver   Date         Author               Modification
 * 1.0   02/02/2021   daniel@hyphen8.com   Initial Version
**/
public with sharing class boardLWCTagManagement {
    

    /**
    * @description          method to return a list of available tags for an individual card
    * @param                string recordId board ID passed from LWC Component get recordId
    * @param                List<BoardWrapper.TagsWrapper> currentTags  current tags as selected on LWC Card record card.tags
    * @return               List<BoardWrapper.TagsWrapper> 
    **/
    @AuraEnabled
    public static List<BoardWrapper.TagsWrapper> getAvailableTags(String recordId, List<BoardWrapper.TagsWrapper> currentTags)
    {
        Set<ID> setOfIDs = new Set<ID>();
        List<BoardWrapper.TagsWrapper> returnTagsWrapper = new List<BoardWrapper.TagsWrapper>();   

        for(BoardWrapper.TagsWrapper tag:currentTags){
            setOfIDs.add(tag.boardTagId);
        }
        
        //Query list of all tags
        List<Board_Tags__c> boardTags = [SELECT Id, Colour__c, Name FROM Board_Tags__c WHERE Board__c = :recordId AND ID NOT IN :setOfIDs];

        for(Board_Tags__c boardTag : boardTags) {

             BoardWrapper.TagsWrapper tagWrapper = new BoardWrapper.TagsWrapper();
             tagWrapper.boardTagId = boardTag.id;                        
             tagWrapper.tagColour = boardTag.colour__c;
             tagWrapper.tagName = boardTag.Name;
             returnTagsWrapper.add(tagWrapper);             
        }

        return returnTagsWrapper;
                    
    }
}