force-app/main/default/objects/Board__c/Board__c.object-meta.xml
<CustomObject>
    <description>This is used for storing projects or work against.</description>
    <label>Board</label>
    <nameField>
        <label>Board Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Boards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Board__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>Provide a description for this board</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Card__c/Card__c.object-meta.xml
<CustomObject>
    <description>These are child records against a board and are used to store work items</description>
    <label>Card</label>
    <nameField>
        <label>Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Card__c/fields/Board__c.field-meta.xml
<CustomField>
    <fullName>Board__c</fullName>
    <label>Board</label>
    <referenceTo>Board__c</referenceTo>
    <relationshipLabel>Cards</relationshipLabel>
    <relationshipName>Cards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Card__c/fields/Card_Number__c.field-meta.xml
<CustomField>
    <fullName>Card_Number__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Card Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Card__c/fields/Card_Status__c.field-meta.xml
<CustomField>
    <fullName>Card_Status__c</fullName>
    <label>Card Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Live</fullName>
                <default>true</default>
                <label>Live</label>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Card__c/fields/Due_Date_Passed__c.field-meta.xml
<CustomField>
    <fullName>Due_Date_Passed__c</fullName>
    <formula>IF(Due_Date__c&gt; TODAY(), FALSE, TRUE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Due Date Passed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Card__c/fields/Lane__c.field-meta.xml
<CustomField>
    <fullName>Lane__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lane</label>
    <referenceTo>Lane__c</referenceTo>
    <relationshipLabel>Cards</relationshipLabel>
    <relationshipName>Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Card_Member__c/Card_Member__c.object-meta.xml
<CustomObject>
    <description>These are the members for a specific card.</description>
    <label>Card Member</label>
    <nameField>
        <displayFormat>CMID-{000000000}</displayFormat>
        <label>Card Member ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Card Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Card_Member__c/fields/Card__c.field-meta.xml
<CustomField>
    <fullName>Card__c</fullName>
    <label>Card</label>
    <referenceTo>Card__c</referenceTo>
    <relationshipLabel>Card Members</relationshipLabel>
    <relationshipName>Card_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Card_Member__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Card_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Card_Tag__c/Card_Tag__c.object-meta.xml
<CustomObject>
    <description>This is for tagging or categorisation of cards</description>
    <label>Card Tag</label>
    <nameField>
        <displayFormat>CTID-{000000000}</displayFormat>
        <label>Card Tag ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Card Tags</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Card_Tag__c/fields/Board_Tag__c.field-meta.xml
<CustomField>
    <fullName>Board_Tag__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Board Tag</label>
    <referenceTo>Board_Tags__c</referenceTo>
    <relationshipLabel>Card Tags</relationshipLabel>
    <relationshipName>Card_Tags</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Card_Tag__c/fields/Card__c.field-meta.xml
<CustomField>
    <fullName>Card__c</fullName>
    <label>Card</label>
    <referenceTo>Card__c</referenceTo>
    <relationshipLabel>Card Tags</relationshipLabel>
    <relationshipName>Card_Tags</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Card_Tag__c/fields/Tag_Colour__c.field-meta.xml
<CustomField>
    <fullName>Tag_Colour__c</fullName>
    <formula>TEXT(Board_Tag__r.Colour__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tag Colour</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Card_Tag__c/fields/Tag_Name__c.field-meta.xml
<CustomField>
    <fullName>Tag_Name__c</fullName>
    <formula>Board_Tag__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tag Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lane__c/Lane__c.object-meta.xml
<CustomObject>
    <description>These are used to provide swimming lane elements within a board</description>
    <label>Lane</label>
    <nameField>
        <label>Lane Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lanes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Lane__c/fields/Board__c.field-meta.xml
<CustomField>
    <fullName>Board__c</fullName>
    <inlineHelpText>This is the board that this Lane is related to</inlineHelpText>
    <label>Board</label>
    <referenceTo>Board__c</referenceTo>
    <relationshipLabel>Lanes</relationshipLabel>
    <relationshipName>Lanes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/boardLWCMethods.cls
/**
 * @description       : Series of methods to support the management of boards within Salesforce
 * @author            : daniel@hyphen8.com
 * @last modified on  : 02/02/2021
 * @last modified by  : daniel@hyphen8.com
 * Modifications Log 
 * Ver   Date         Author               Modification
 * 1.0   19/01/2021   daniel@hyphen8.com   Initial Version
**/
public with sharing class boardLWCMethods {

    @AuraEnabled
    public static BoardWrapper.CardWrapper getCard(string recordId){
        try {
            system.debug('recordId > ' + recordId);

            Card__c card = [SELECT ID, Lane__c, Name, Order__c, Card_Number__c, Due_Date__c, Due_Date_Passed__c, Description__c, (SELECT ID, Card__c, User__c FROM Card_Members__r), (SELECT ID, Card__c, Tag_Colour__c, Tag_Name__c, Board_Tag__c FROM Card_Tags__r) FROM Card__c WHERE ID=:recordId];

            Map<ID, List<BoardWrapper.MemberWrapper>> mapOfMembers;
            if(card.Card_Members__r != null){
                mapOfMembers = boardLWCHelperMethods.getCardMapOfMembers(card.Card_Members__r);
            } else {
                mapOfMembers = new Map<ID, List<BoardWrapper.MemberWrapper>>();
            }
            
            List<BoardWrapper.MemberWrapper> thisCardMembers;

            if(mapOfMembers.containsKey(card.Id)){
                thisCardMembers = mapOfMembers.get(card.Id);
            } else {
                thisCardMembers = new List<BoardWrapper.MemberWrapper>();
            }
            
            Map<ID, List<BoardWrapper.TagsWrapper>> mapOfTags;
            if(card.Card_Tags__r != null){
                mapOfTags = boardLWCHelperMethods.getCardMapOfTags(card.Card_Tags__r);
            } else {
                mapOfTags = new Map<ID, List<BoardWrapper.TagsWrapper>>();
            }
            
            List<BoardWrapper.TagsWrapper> thisCardTags;
            if(mapOfTags.containsKey(card.Id)){
                thisCardTags = mapOfTags.get(card.Id);
            } else {
                thisCardTags = new List<BoardWrapper.TagsWrapper>();
            }

            BoardWrapper.CardWrapper cw = new BoardWrapper.CardWrapper();
            cw.members = thisCardMembers;
            cw.tags = thisCardTags;
            cw.cardDueDate = card.Due_Date__c;
            cw.cardDueDatePassed = card.Due_Date_Passed__c;
            cw.cardId = card.Id;
            cw.cardName = card.Name;
            cw.cardNumber = integer.valueOf(card.Card_Number__c);
            cw.cardOrder = integer.valueOf(card.Order__c);
            cw.cardDescription = card.Description__c;
            return cw;
            
        } catch (Exception e) {
       
            throw new AuraHandledException(e.getMessage());
       
        }
    }


    /**
     * @description     method to delete or archive a card
     * @param           string recordId
     * @param           string type
     * @return          string
    **/
    @AuraEnabled
    public static string deleteArchiveCard(string recordId, string type){
        try {

            ID laneID = [SELECT ID FROM Lane__c WHERE Name=:type AND Order__c =:0 LIMIT 1].Id;

            Card__c card = [SELECT ID, Lane__c, Card_Status__c, Order__c FROM Card__c WHERE ID=:recordId];

            List<Card__c> listOfExistingCards = [SELECT ID, Card_Status__c, Order__c FROM Card__c WHERE Lane__c =: card.Lane__c AND ID !=:recordId AND Card_Status__c=:'Live' ORDER BY Order__c ASC];
            
            List<Card__c> updateList = new List<Card__c>();

            integer cardCount = 1;

            for(Card__c liveCard:listOfExistingCards) {
                liveCard.Order__c = cardCount;
                cardCount = cardCount + 1;
                updateList.add(liveCard);
            }

            database.update(updateList);
            
            card.Lane__c = laneID;
            card.Card_Status__c = type;
            card.Order__c = null;
            update card;

            return 'Success';
            
        } catch (Exception e) {
        
            throw new AuraHandledException(e.getMessage());
        
        }
    }


    /**
     * @description     method to support drag events
     * @param           string movingCardId
     * @param           string laneId
     * @param           string newParentCardId
     * @return          boolean
    **/
    @AuraEnabled
    public static boolean supportDragCardMethod(string movingCardId, string laneId, string newParentCardId) {
        try {

            if(newParentCardId == 'NoCard') {
            
                Card__c card = new Card__c(ID=movingCardId);
            
                card.Order__c = 1;
            
                card.Lane__c = laneId;
            
                update card;
            
            } else if (newParentCardId == 'TopCard') {

                List<Card__c> listOfCards = [SELECT ID, Order__c, Card_Status__c FROM Card__c WHERE Lane__c=:laneId AND ID !=: movingCardId AND Card_Status__c=:'Live' ORDER BY Order__c ASC];

                integer cardCount = 2;

                List<Card__c> updateList = new List<Card__c>();

                Card__c currentCard = new Card__c(ID=movingCardId);
            
                currentCard.Order__c = 1;
            
                currentCard.Lane__c = laneId;
            
                updateList.add(currentCard);

                for(Card__c card:listOfCards) {
            
                    card.Order__c = cardCount;
            
                    cardCount = cardCount + 1;
            
                    updateList.add(card);
            
                }

                database.update(updateList);

            } else {

                List<Card__c> listOfCards = [SELECT ID, Order__c, Card_Status__c FROM Card__c WHERE Lane__c=:laneId AND ID !=: movingCardId AND Card_Status__c=:'Live' ORDER BY Order__c ASC];

                integer cardOrder = 1;

                List<Card__c> updateList = new List<Card__c>();

                for(Card__c card:listOfCards){
            
                    card.Order__c = cardOrder;
            
                    cardOrder = cardOrder + 1;
            
                    updateList.add(card);
            
                    if(card.Id == newParentCardId){
            
                        Card__c movingCard = new Card__c(ID=movingCardId);
            
                        movingCard.Lane__c = laneId;
            
                        movingCard.Order__c = cardOrder;
            
                        cardOrder = cardOrder + 1;
            
                        updateList.add(movingCard);
            
                    }
            
                }

                database.update(updateList);

            }

            return true;
            
        } catch (Exception e) {

            throw new AuraHandledException(e.getMessage());

        }

    }


    /**
    * @description      simple method to return a list of lanes for a given board
    * @author           daniel@hyphen8.com | 19/01/2021 
    * @param            recordId - board ID
    * @return           List<Lane__c> 
    **/
    @AuraEnabled
    public static BoardWrapper getListOfLanes(string recordId) {
        
        try {

            List<Lane__c> getListOfLane = [SELECT ID, Name, Order__c FROM Lane__c WHERE Board__c=:recordId AND Order__c != 0 ORDER BY Order__c ASC];
        
            List<Card__c> getListOfCards = [SELECT ID, Lane__c, Name, Order__c, Card_Number__c, Due_Date__c, Due_Date_Passed__c, Card_Status__c FROM Card__c WHERE Board__c=:recordId AND Card_Status__c=:'Live' ORDER BY Order__c ASC];

            Set<ID> cardIDs = new Set<ID>();

            Map<ID, List<Card__c>> mapOfCards = new Map<ID, List<Card__c>>();

            for(Card__c card:getListOfCards){
        
                cardIDs.add(card.Id);
        
                List<Card__c> cards;
        
                if(mapOfCards.containsKey(card.Lane__c)){
        
                    cards = mapOfCards.get(card.Lane__c);
        
                } else {
        
                    cards = new List<Card__c>();
        
                }
        
                cards.add(card);
        
                mapOfCards.put(card.Lane__c, cards);
        
            }

            List<Card_Member__c> getListOfMembers = [SELECT ID, Card__c, User__c FROM Card_Member__c WHERE Card__c IN:cardIDs];

            Map<ID, List<BoardWrapper.MemberWrapper>> mapOfMembers = boardLWCHelperMethods.getCardMapOfMembers(getListOfMembers);

            List<Card_Tag__c> getListOfTags = [SELECT ID, Card__c, Tag_Colour__c, Tag_Name__c, Board_Tag__c FROM Card_Tag__c WHERE Card__c IN:cardIDs];

            Map<ID, List<BoardWrapper.TagsWrapper>> mapOfTags = boardLWCHelperMethods.getCardMapOfTags(getListOfTags);

            BoardWrapper bWrapper = new BoardWrapper();

            List<BoardWrapper.LaneWrapper> laneWrappers = new List<BoardWrapper.LaneWrapper>();

            for(Lane__c lane:getListOfLane){

                BoardWrapper.LaneWrapper lw = new BoardWrapper.LaneWrapper();

                lw.laneName = lane.Name;

                lw.laneID = lane.Id;

                lw.laneOrder = integer.valueOf(lane.Order__c);

                if(mapOfCards.containsKey(lane.Id)){
                
                    List<Card__c> cards = mapOfCards.get(lane.Id);
                
                    List<BoardWrapper.CardWrapper> cardWrappers = new List<BoardWrapper.CardWrapper>();
                
                    for(Card__c card:cards){
                
                        BoardWrapper.CardWrapper cWrapper = new BoardWrapper.CardWrapper();
                
                        cWrapper.cardId = card.Id;

                        cWrapper.cardDueDate = card.Due_Date__c;
                        
                        cWrapper.cardDueDatePassed = card.Due_Date_Passed__c;
                        
                        cWrapper.cardName = card.Name;
                        
                        cWrapper.cardNumber = integer.valueOf(card.Card_Number__c);
                        
                        cWrapper.cardOrder = integer.valueOf(card.Order__c);

                        List<BoardWrapper.MemberWrapper> thisCardMembers;

                        if(mapOfMembers.containsKey(card.Id)){
                            thisCardMembers = mapOfMembers.get(card.Id);
                        } else {
                            thisCardMembers = new List<BoardWrapper.MemberWrapper>();
                        }

                        cWrapper.members = thisCardMembers;

                        List<BoardWrapper.TagsWrapper> thisCardTags;
                        if(mapOfTags.containsKey(card.Id)){
                            thisCardTags = mapOfTags.get(card.Id);
                        } else {
                            thisCardTags = new List<BoardWrapper.TagsWrapper>();
                        }
                        cWrapper.tags = thisCardTags;
                        
                        
                        cardWrappers.add(cWrapper);
                    }

                    
                    if(cardWrappers.size() > 0){
                    
                        lw.cards = cardWrappers;
                    
                    }
                }
                
                laneWrappers.add(lw);
            
            }

            bWrapper.lanes = laneWrappers;
            
            return bWrapper;

        } catch (Exception e) {

            throw new AuraHandledException(e.getMessage());

        }

    }

}