force-app/main/default/objects/Board__c/Board__c.object-meta.xml
<CustomObject>
    <description>This is used for storing projects or work against.</description>
    <label>Board</label>
    <nameField>
        <label>Board Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Boards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Board_Tags__c/Board_Tags__c.object-meta.xml
<CustomObject>
    <description>This object is used to setup tags on a project</description>
    <label>Board Tag</label>
    <nameField>
        <label>Board Tags Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Board Tags</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Board_Tags__c/fields/Board__c.field-meta.xml
<CustomField>
    <fullName>Board__c</fullName>
    <label>Board</label>
    <referenceTo>Board__c</referenceTo>
    <relationshipLabel>Board Tags</relationshipLabel>
    <relationshipName>Board_Tags</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Card__c/Card__c.object-meta.xml
<CustomObject>
    <description>These are child records against a board and are used to store work items</description>
    <label>Card</label>
    <nameField>
        <label>Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Card__c/fields/Board__c.field-meta.xml
<CustomField>
    <fullName>Board__c</fullName>
    <label>Board</label>
    <referenceTo>Board__c</referenceTo>
    <relationshipLabel>Cards</relationshipLabel>
    <relationshipName>Cards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Card_Tag__c/Card_Tag__c.object-meta.xml
<CustomObject>
    <description>This is for tagging or categorisation of cards</description>
    <label>Card Tag</label>
    <nameField>
        <displayFormat>CTID-{000000000}</displayFormat>
        <label>Card Tag ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Card Tags</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Card_Tag__c/fields/Board_Tag__c.field-meta.xml
<CustomField>
    <fullName>Board_Tag__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Board Tag</label>
    <referenceTo>Board_Tags__c</referenceTo>
    <relationshipLabel>Card Tags</relationshipLabel>
    <relationshipName>Card_Tags</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Card_Tag__c/fields/Card__c.field-meta.xml
<CustomField>
    <fullName>Card__c</fullName>
    <label>Card</label>
    <referenceTo>Card__c</referenceTo>
    <relationshipLabel>Card Tags</relationshipLabel>
    <relationshipName>Card_Tags</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/boardLWCTagManagement_Test.cls
/**
 * @description  : Test class for boardLWCTagManagement
 * @author       : simon@hyphen8.com
 * @date         : 09-02-2021
**/
@IsTest
public class boardLWCTagManagement_Test {
    @IsTest
    static void testGetAvailableTagsNoCurrent(){
        Board__c board = new Board__c(
            Name = 'Test Board'
        );
        insert board;

        List<Board_Tags__c> boardTags = new List<Board_Tags__c>();
        for (Integer i = 0 ; i < 3 ; i++){
            boardTags.add(new Board_Tags__c(
                Board__c = board.Id,
                Name = 'Board Tag ' + i
            ));
        }

        insert boardTags;

        List<BoardWrapper.TagsWrapper> boardTagsFromClass;

        Test.startTest();
        boardTagsFromClass = boardLWCTagManagement.getAvailableTags(board.Id, new List<BoardWrapper.TagsWrapper>());
        Test.stopTest();

        System.assertEquals(boardTagsFromClass.size(), 3, 'Expected number of Tags returned');
    }

    @IsTest
    static void testGetAvailableTagsWithCurrent(){
        Board__c board = new Board__c(
            Name = 'Test Board'
        );
        insert board;

        Card__c card = new Card__c(
            board__c = board.Id,
            name='Test Card'
        );
        insert card;

        List<Board_Tags__c> boardTags = new List<Board_Tags__c>();
        for (Integer i = 0 ; i < 3 ; i++){
            boardTags.add(new Board_Tags__c(
                Board__c = board.Id,
                Name = 'Board Tag ' + i
            ));
        }
        insert boardTags;
        
        List<Card_Tag__c> cardTags = new List<Card_Tag__c>();
        for (Integer i = 0 ; i < 2 ; i++){
            Board_Tags__c boardTag = boardTags.get(i);
            cardTags.add(new Card_Tag__c(
                card__c = card.Id,
                board_Tag__c = boardTag.Id
            ));
        }

        insert cardTags;
        
        List<BoardWrapper.TagsWrapper> boardWrapperList = new List<BoardWrapper.TagsWrapper>();

        for(Card_Tag__c cardTag : cardTags) {

            BoardWrapper.TagsWrapper tag = new BoardWrapper.TagsWrapper();                
            tag.boardTagId = cardTag.Board_Tag__c;
            tag.tagId = cardTag.id;
            boardWrapperList.add(tag) ;

        }

        //  Map<ID, List<BoardWrapper.TagsWrapper>> mapOfTags = boardLWCHelperMethods.getCardMapOfTags(cardTags);

        List<BoardWrapper.TagsWrapper> boardTagsFromClass;

        Test.startTest();
            // boardTagsFromClass = boardLWCTagManagement.getAvailableTags(board.Id, mapOfTags.get(card.Id));
           boardTagsFromClass = boardLWCTagManagement.getAvailableTags(board.Id, boardWrapperList);
        Test.stopTest();

        System.assertEquals(boardTagsFromClass.size(), 1, 'Expected number of Tags returned');
    }
    
}