force-app/main/default/objects/Card__c/Card__c.object-meta.xml
<CustomObject>
    <description>These are child records against a board and are used to store work items</description>
    <label>Card</label>
    <nameField>
        <label>Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Card_Member__c/Card_Member__c.object-meta.xml
<CustomObject>
    <description>These are the members for a specific card.</description>
    <label>Card Member</label>
    <nameField>
        <displayFormat>CMID-{000000000}</displayFormat>
        <label>Card Member ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Card Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Card_Member__c/fields/Card__c.field-meta.xml
<CustomField>
    <fullName>Card__c</fullName>
    <label>Card</label>
    <referenceTo>Card__c</referenceTo>
    <relationshipLabel>Card Members</relationshipLabel>
    <relationshipName>Card_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Card_Member__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Card_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Card_Tag__c/Card_Tag__c.object-meta.xml
<CustomObject>
    <description>This is for tagging or categorisation of cards</description>
    <label>Card Tag</label>
    <nameField>
        <displayFormat>CTID-{000000000}</displayFormat>
        <label>Card Tag ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Card Tags</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Card_Tag__c/fields/Board_Tag__c.field-meta.xml
<CustomField>
    <fullName>Board_Tag__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Board Tag</label>
    <referenceTo>Board_Tags__c</referenceTo>
    <relationshipLabel>Card Tags</relationshipLabel>
    <relationshipName>Card_Tags</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Card_Tag__c/fields/Card__c.field-meta.xml
<CustomField>
    <fullName>Card__c</fullName>
    <label>Card</label>
    <referenceTo>Card__c</referenceTo>
    <relationshipLabel>Card Tags</relationshipLabel>
    <relationshipName>Card_Tags</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Card_Tag__c/fields/Tag_Colour__c.field-meta.xml
<CustomField>
    <fullName>Tag_Colour__c</fullName>
    <formula>TEXT(Board_Tag__r.Colour__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tag Colour</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Card_Tag__c/fields/Tag_Name__c.field-meta.xml
<CustomField>
    <fullName>Tag_Name__c</fullName>
    <formula>Board_Tag__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tag Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/boardLWCHelperMethods.cls
/**
 * @description       : helper reusabled methods
 * @author            : daniel@hyphen8.com
 * @last modified on  : 02/02/2021
 * @last modified by  : daniel@hyphen8.com
 * Modifications Log 
 * Ver   Date         Author               Modification
 * 1.0   24/01/2021   daniel@hyphen8.com   Initial Version
**/
public with sharing class boardLWCHelperMethods {
    
    
    /**
    * @description          method converts a list of card members in a Map of BoardWrapper.MemberWrapper broken where ID = cardId
    * @param                List<Card_Member__c> cardMembers 
    * @return               Map<ID, List<BoardWrapper.MemberWrapper>> 
    **/
    public static Map<ID, List<BoardWrapper.MemberWrapper>> getCardMapOfMembers(List<Card_Member__c> cardMembers){

        Map<ID, List<BoardWrapper.MemberWrapper>> returnMap = new Map<ID, List<BoardWrapper.MemberWrapper>>();

        Set<ID> userIDs = new Set<ID>();

        for(Card_Member__c cm:cardMembers){

            userIDs.add(cm.User__c);

        }

        Map<ID, User> mapOfUsers = new Map<ID, User>([SELECT ID, Name, SmallPhotoUrl FROM User WHERE ID in:userIDs]);

        for(Card_Member__c cm:cardMembers){

            User user = mapOfUsers.get(cm.User__c);

            List<BoardWrapper.MemberWrapper> cardUsers;

            if(returnMap.containsKey(cm.Card__c)){

                cardUsers = returnMap.get(cm.Card__c);

            } else {

                cardUsers = new List<BoardWrapper.MemberWrapper>();

            }

            BoardWrapper.MemberWrapper memberWrapper = new BoardWrapper.MemberWrapper();
            memberWrapper.userImageURL = user.SmallPhotoUrl;
            memberWrapper.userName = user.Name;
            memberWrapper.userName = user.Id;

            cardUsers.add(memberWrapper);

            returnMap.put(cm.Card__c, cardUsers);

        }

        return returnMap;
    }


    public static Map<ID, List<BoardWrapper.TagsWrapper>> getCardMapOfTags(List<Card_Tag__c> cardTags){

        Map<ID, List<BoardWrapper.TagsWrapper>> returnMap = new Map<ID, List<BoardWrapper.TagsWrapper>>();

        for(Card_Tag__c ct:cardTags){
            List<BoardWrapper.TagsWrapper> tags;
            if(returnMap.containsKey(ct.Card__c)){
                tags = returnMap.get(ct.Card__c);
            } else {
                tags = new List<BoardWrapper.TagsWrapper>();
            }

            BoardWrapper.TagsWrapper tag = new BoardWrapper.TagsWrapper();
            tag.tagColour = 'tagContainer ' + ct.Tag_Colour__c;
            tag.tagName = ct.Tag_Name__c;
            tag.boardTagId = ct.Board_Tag__c;
            tag.tagId = ct.Id;

            tags.add(tag);

            returnMap.put(ct.Card__c, tags);
        }

        return returnMap;
    }
}